### ISSUE TITLE
Groups Support [QUESTION]

### ISSUE THREAD

**Issue by Jacobinoo** [RTann/libsignal-go#38]
Hi. I just want to know whether groups are finally supported. Thanks! @RTann

**Comment by RTann** [comment]
Hi! Apologies for the delay! Thank you for your interest in this library.

Yes! As of https://github.com/RTann/libsignal-go/pull/13 groups are supported. See https://github.com/RTann/libsignal-go/blob/main/protocol/tests/group_session_test.go for example uses.

**Comment by Jacobinoo** [comment]
Thanks a lot!!

**Comment by RazaGR** [comment]
Thanks RTann , guess [README](https://github.com/RTann/libsignal-go/blob/main/README.md) should be updated with this info, currently it says 

```
Only libsignal-protocol is implemented at this time, and it does not support groups at this time.
```

**Comment by Jacobinoo** [comment]
> Thanks RTann , guess [README](https://github.com/RTann/libsignal-go/blob/main/README.md) should be updated with this info, currently it says
> 
> ```
> Only libsignal-protocol is implemented at this time, and it does not support groups at this time.
> ```

@RTann PR #43
